name: Test Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v4
      
    - name : Install Packages 
      run : pip install pytest
      
    - name : Run tests 
      run : pytest tests/
